Taken from https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/#

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [3]:
a1 = np.array([1, 2, 3, 4])

print(a1)  # [1, 2, 3, 4]
print(a1[0]) # 1
print(a1[2]) # 3

[1 2 3 4]
1
3


In [4]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print('a2 = ')
img = mpimg.imread('2d-array.png')
imgplot = plt.imshow(img)
plt.axis('off')
plt.show()

a2 = 


FileNotFoundError: [Errno 2] No such file or directory: '2d-array.png'

The figure above depicts how array a2 looks like and how indexes i and j can be used to search/store values in the array.

In [ ]:
# The example picks row 2, column 1, which has the value 8.
print(a2[2, 1]) # 8

# Picking a row or column

In [ ]:
# If you supply a single index in a 2d array, it will pick a row (i value) and return that as a rank 1 array.
print(a2[2]) # [7, 8, 9]

In [ ]:
# To pick up a single columm
print(a2[:, 1]) # [2, 5, 8]

The syntax above means:

* for the i value, take all values (: is a full slice, from start to end)
* for the j value take 1

In [ ]:
print('a2_col = ')
img = mpimg.imread('2d-array-col-1.png')
imgplot = plt.imshow(img)
plt.axis('off')
plt.show()

In [ ]:
# To create a 3d array
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

print(a3)

In [ ]:
print('a3 = ')
img = mpimg.imread('3d-array.png')
imgplot = plt.imshow(img)
plt.axis('off')
plt.show()

A 3D array is like a stack of matrices:

* The first index, i, selects the matrix
* The second index, j, selects the row
* The third index, k, selects the column

In [ ]:
# To pick up a value in the 3d array
print(a3[2, 0, 1]) # 31

# Slicing an array

You can slice a numpy array in a similar way to slicing a list - except you can do it in more than one dimension. Let's recap slicing method in lists first.

In [6]:
a = [10, 11, 12, 13, 14]
print(a)

[10, 11, 12, 13, 14]


In [7]:
# b is a sub-list of a
b = a[1:4]    # [11, 12, 13]
print(b)

[11, 12, 13]


The slice notation specifies a start and end value [start:end:step] and copies the list from start up to but not including end. If step is not specified, it is taken as 1.

In [8]:
# If we omit the start, the slice start at the beginning of the list
c = a[:3]    # [10, 11, 12]
print(c)

[10, 11, 12]


In [ ]:
# If we omit the end, so the slice continues to the end of the list
d = a[2:]    # [12, 13, 14]
print(d)

# If we omit both the slice created is a copy of the entire list
e = a[:]     # [10, 11, 12, 13, 14]
print(e)

# Slicing 1D numpy arrays

Slicing a 1D numpy array is almost exactly the same as slicing a list...

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

b1 = a1[1:4]
print(b1)  # [2, 3, 4]

# copying a1 to c1
c1 = np.copy(a1)
print(c1)

# BUT it is important to note that a1 and b1 are now POINTERS, meaning: 

So if you change an element in b1, a1 will be affected (and vice versa), e.g.:

In [ ]:
b1[1] = 10
print(b1)  # [2, 10, 4]
print(a1) # [1, 2, 10, 4, 5]

# It is also said that 'b1 is a view of the data in a1'.

In [ ]:
# If you still need the original data in a1, we work with copies of the arrays (as done in c1),
# prior to altering a1 or b1.

print(c1) # c1 still stores the original a1.

In [ ]:
# Slicing 2D array in both axes to obtain a rectangular subset of the original array
a2 = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

print(a2[1:,2:4])  # [[17 18]
                   #  [22 23]
                   #  [27 28]]

In [ ]:
print('a2_slice = ')
img = mpimg.imread('2d-array-slice.png')
imgplot = plt.imshow(img)
plt.axis('off')
plt.show()

# Testing full slicing

In [9]:
v = np.arange(10)
print(v)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(v[3:])

[3 4 5 6 7 8 9]


In [11]:
print(v[:6])

[0 1 2 3 4 5]


In [12]:
print(v[3:6])

[3 4 5]


In [13]:
# note that if the slices are of the same size, you can perform operations with them, for instance, to perform a element-wise
# sum without the need of any loops.
slice1 = v[:3]
print(slice1)

slice2 = v[3:6]
print(slice2)
print('------')
slice_sum = slice1 + slice2
print(slice_sum)

[0 1 2]
[3 4 5]
------
[3 5 7]
